./video/fbdev/built-in.o
./video/fbdev/core/fb_notify.o
./video/fbdev/core/built-in.o
./video/fbdev/omap2/dss/built-in.o
./video/fbdev/omap2/built-in.o
./video/fbdev/omap2/displays-new/built-in.o
./video/built-in.o
./video/backlight/built-in.o
./video/rockchip/built-in.o
