root@7668e5b50427:/home/project# ./build.sh uboot
============Start build uboot============
TARGET_UBOOT_CONFIG=roc-rk3308-cc
=========================================
make for roc-rk3308-cc_defconfig by -j16
#
# configuration written to .config
#
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk.dep
  GEN     include/autoconf.mk
  CHK     include/config/uboot.release
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  CHK     include/config.h
  CFG     u-boot.cfg
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/generic-asm-offsets.h
  CHK     include/generated/asm-offsets.h
  HOSTCC  tools/mkenvimage.o
  HOSTCC  tools/fit_image.o
  HOSTCC  tools/image-host.o
  HOSTCC  tools/dumpimage.o
  HOSTCC  tools/mkimage.o
  HOSTLD  tools/mkenvimage
  HOSTLD  tools/dumpimage
  HOSTLD  tools/mkimage
  CC      arch/arm/cpu/armv8/fwcall.o
  LD      arch/arm/cpu/armv8/built-in.o
  CC      common/main.o
  CC      lib/smbios.o
  CC      lib/display_options.o
  CC      cmd/version.o
  CC      lib/efi_loader/helloworld.o
  LD      cmd/built-in.o
  LD      lib/efi_loader/helloworld.so
  LD      common/built-in.o
  OBJCOPY lib/efi_loader/helloworld.efi
  LD      lib/built-in.o
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot-nodtb.bin
  SYM     u-boot.sym
start=$(/home/project/prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-nm u-boot | grep __rel_dyn_start | cut -f 1 -d ' '); end=$(/home/project/prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-nm u-boot | grep __rel_dyn_end | cut -f 1 -d ' '); tools/relocate-rela u-boot-nodtb.bin 0x00600000 $start $end
make[2]: 'arch/arm/dts/rk3308-evb.dtb' is up to date.
  CAT     u-boot-dtb.bin
  COPY    u-boot.bin
  MKIMAGE u-boot.img
  MKIMAGE u-boot-dtb.img
  CFGCHK  u-boot.cfg

 load addr is 0x600000!
pack input ./u-boot.bin
pack file size: 601081
crc = 0xd1bbce6f
pack uboot.img success!
pack uboot okay! Input: ./u-boot.bin
out:rk3308_loader_v1.24.108.bin
fix opt:rk3308_loader_v1.24.108.bin
merge success(rk3308_loader_v1.24.108.bin)
pack loader okay! Input: /home/project/rkbin/RKBOOT/RK3308MINIALL.ini
/home/project/u-boot
out:trust.img
merge success(trust.img)
/home/project/u-boot
pack trust okay! Input: /home/project/rkbin/RKTRUST/RK3308TRUST.ini

Platform RK3308 is build OK, with new .config(make roc-rk3308-cc_defconfig)
/home/project
====Build uboot ok!====
root@7668e5b50427:/home/project# 
